"""Initial schema setup: Country, Product, and Tariff tables

Revision ID: 5f4614d229de
Revises: 
Create Date: 2025-11-10 18:06:54.343798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f4614d229de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_economicindicator_country_id'), table_name='economicindicator')
    op.drop_index(op.f('ix_economicindicator_indicator_code'), table_name='economicindicator')
    op.drop_table('economicindicator')
    op.drop_constraint(op.f('product_code_key'), 'product', type_='unique')
    op.create_index(op.f('ix_product_code'), 'product', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_code'), table_name='product')
    op.create_unique_constraint(op.f('product_code_key'), 'product', ['code'], postgresql_nulls_not_distinct=False)
    op.create_table('economicindicator',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('indicator_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['country.id'], name=op.f('economicindicator_country_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('economicindicator_pkey')),
    sa.UniqueConstraint('country_id', 'indicator_code', 'date', name=op.f('uc_econ_data'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_economicindicator_indicator_code'), 'economicindicator', ['indicator_code'], unique=False)
    op.create_index(op.f('ix_economicindicator_country_id'), 'economicindicator', ['country_id'], unique=False)
    # ### end Alembic commands ###
